import FWCore.ParameterSet.Config as cms

tHweights = cms.VPSet(
  # 16 weights
  cms.PSet(kt = cms.double(-3.0),  kv = cms.double(1.0), idx = cms.uint32(0)),
  cms.PSet(kt = cms.double(-2.0),  kv = cms.double(1.0), idx = cms.uint32(1)),
  cms.PSet(kt = cms.double(-1.5),  kv = cms.double(1.0), idx = cms.uint32(2)),
  cms.PSet(kt = cms.double(-1.25), kv = cms.double(1.0), idx = cms.uint32(3)),
  cms.PSet(kt = cms.double(-0.75), kv = cms.double(1.0), idx = cms.uint32(4)),
  cms.PSet(kt = cms.double(-0.5),  kv = cms.double(1.0), idx = cms.uint32(5)),
  cms.PSet(kt = cms.double(-0.25), kv = cms.double(1.0), idx = cms.uint32(6)),
  cms.PSet(kt = cms.double(0.0),   kv = cms.double(1.0), idx = cms.uint32(7)),
  cms.PSet(kt = cms.double(0.25),  kv = cms.double(1.0), idx = cms.uint32(8)),
  cms.PSet(kt = cms.double(0.5),   kv = cms.double(1.0), idx = cms.uint32(9)),
  cms.PSet(kt = cms.double(0.75),  kv = cms.double(1.0), idx = cms.uint32(10)),
  cms.PSet(kt = cms.double(1.0),   kv = cms.double(1.0), idx = cms.uint32(11)),
  cms.PSet(kt = cms.double(1.25),  kv = cms.double(1.0), idx = cms.uint32(12)),
  cms.PSet(kt = cms.double(1.5),   kv = cms.double(1.0), idx = cms.uint32(13)),
  cms.PSet(kt = cms.double(2.0),   kv = cms.double(1.0), idx = cms.uint32(14)),
  cms.PSet(kt = cms.double(3.0),   kv = cms.double(1.0), idx = cms.uint32(15)),
  # 17 weights
  cms.PSet(kt = cms.double(-3.0),  kv = cms.double(1.5), idx = cms.uint32(16)),
  cms.PSet(kt = cms.double(-2.0),  kv = cms.double(1.5), idx = cms.uint32(17)),
  cms.PSet(kt = cms.double(-1.5),  kv = cms.double(1.5), idx = cms.uint32(18)),
  cms.PSet(kt = cms.double(-1.25), kv = cms.double(1.5), idx = cms.uint32(19)),
  cms.PSet(kt = cms.double(-1.0),  kv = cms.double(1.5), idx = cms.uint32(20)),
  cms.PSet(kt = cms.double(-0.75), kv = cms.double(1.5), idx = cms.uint32(21)),
  cms.PSet(kt = cms.double(-0.5),  kv = cms.double(1.5), idx = cms.uint32(22)),
  cms.PSet(kt = cms.double(-0.25), kv = cms.double(1.5), idx = cms.uint32(23)),
  cms.PSet(kt = cms.double(0.0),   kv = cms.double(1.5), idx = cms.uint32(24)),
  cms.PSet(kt = cms.double(0.25),  kv = cms.double(1.5), idx = cms.uint32(25)),
  cms.PSet(kt = cms.double(0.5),   kv = cms.double(1.5), idx = cms.uint32(26)),
  cms.PSet(kt = cms.double(0.75),  kv = cms.double(1.5), idx = cms.uint32(27)),
  cms.PSet(kt = cms.double(1.0),   kv = cms.double(1.5), idx = cms.uint32(28)),
  cms.PSet(kt = cms.double(1.25),  kv = cms.double(1.5), idx = cms.uint32(29)),
  cms.PSet(kt = cms.double(1.5),   kv = cms.double(1.5), idx = cms.uint32(30)),
  cms.PSet(kt = cms.double(2.0),   kv = cms.double(1.5), idx = cms.uint32(31)),
  cms.PSet(kt = cms.double(3.0),   kv = cms.double(1.5), idx = cms.uint32(32)),
  # 17 weights
  cms.PSet(kt = cms.double(-3.0),  kv = cms.double(0.5), idx = cms.uint32(33)),
  cms.PSet(kt = cms.double(-2.0),  kv = cms.double(0.5), idx = cms.uint32(34)),
  cms.PSet(kt = cms.double(-1.5),  kv = cms.double(0.5), idx = cms.uint32(35)),
  cms.PSet(kt = cms.double(-1.25), kv = cms.double(0.5), idx = cms.uint32(36)),
  cms.PSet(kt = cms.double(-1.0),  kv = cms.double(0.5), idx = cms.uint32(37)),
  cms.PSet(kt = cms.double(-0.75), kv = cms.double(0.5), idx = cms.uint32(38)),
  cms.PSet(kt = cms.double(-0.5),  kv = cms.double(0.5), idx = cms.uint32(39)),
  cms.PSet(kt = cms.double(-0.25), kv = cms.double(0.5), idx = cms.uint32(40)),
  cms.PSet(kt = cms.double(0.0),   kv = cms.double(0.5), idx = cms.uint32(41)),
  cms.PSet(kt = cms.double(0.25),  kv = cms.double(0.5), idx = cms.uint32(42)),
  cms.PSet(kt = cms.double(0.5),   kv = cms.double(0.5), idx = cms.uint32(43)),
  cms.PSet(kt = cms.double(0.75),  kv = cms.double(0.5), idx = cms.uint32(44)),
  cms.PSet(kt = cms.double(1.0),   kv = cms.double(0.5), idx = cms.uint32(45)),
  cms.PSet(kt = cms.double(1.25),  kv = cms.double(0.5), idx = cms.uint32(46)),
  cms.PSet(kt = cms.double(1.5),   kv = cms.double(0.5), idx = cms.uint32(47)),
  cms.PSet(kt = cms.double(2.0),   kv = cms.double(0.5), idx = cms.uint32(48)),
  cms.PSet(kt = cms.double(3.0),   kv = cms.double(0.5), idx = cms.uint32(49)),
)

thIdxs = [ coupling.idx.value() for coupling in tHweights if coupling.kv == 1.0 ]
